@startuml

!include skinparams.puml

!include GameState.pumlc
!include GameTree.pumlc
!include GameMove.pumlc
!include GameBoard.pumlc

GameState -> GameTree
GameState --> GameMove: Last move
GameTree *--> GameMove
GameMove --> GameMove: Previous move
GameMove *--> GameMove: Next moves
GameBoard <- GameMove

@enduml
